### PR TITLE
GH-22: Add CODEOWNERS

### LINKED ISSUE #22: Add CODEOWNERS
See also: https://github.com/apache/arrow-go/blob/main/.github/CODEOWNERS

### PR DESCRIPTION
**Pull request by wgtmac**
Fixes #22.

### CODE REVIEW

**Comment by wgtmac** [comment]
I just blindly add default codeowners to all files, though I think there are obviously better reviewers for some files. @lidavidm

**Review by lidavidm — APPROVED** [review]

**Comment by lidavidm** [comment]
@laurentgo I haven't seen anything from you, is this OK?

**Review by kou — APPROVED** [review]
+1

**Comment by wgtmac** [comment]
Let me merge this first in order to get PR notifications :)

**Comment by laurentgo** [comment]
Sorry, was out for a couple of days, but yes, it's fine! thanks

**Pull request merged**
